export const FETCH_SINGLE_USER_REQUEST = 'FETCH_SINGLE_USER_REQUEST';
export const FETCH_SINGLE_USER_SUCCESS = 'FETCH_SINGLE_USER_SUCCESS';
export const FETCH_SINGLE_USER_FAILURE = 'FETCH_SINGLE_USER_FAILURE';

export const FETCH_SINGLE_USER_DETAILS_REQUEST = 'FETCH_SINGLE_USER_DETAILS_REQUEST';
export const FETCH_SINGLE_USER_DETAILS_SUCCESS = 'FETCH_SINGLE_USER_DETAILS_SUCCESS';
export const FETCH_SINGLE_USER_DETAILS_FAILURE = 'FETCH_SINGLE_USER_DETAILS_FAILURE';
