export const FETCH_TWEETS_REQUEST = 'FETCH_TWEETS_REQUEST';
export const FETCH_TWEETS_SUCCESS = 'FETCH_TWEETS_SUCCESS';
export const FETCH_TWEETS_FAILURE = 'FETCH_TWEETS_FAILURE';

export const POST_TWEET_REQUEST = 'POST_TWEET_REQUEST';
export const POST_TWEET_SUCCESS = 'POST_TWEET_SUCCESS';
export const POST_TWEET_FAILURE = 'POST_TWEET_FAILURE';

export const UPDATE_TWEET_CLAPS_REQUEST = 'UPDATE_TWEET_CLAPS_REQUEST';
export const UPDATE_TWEET_CLAPS_SUCCESS = 'UPDATE_TWEET_CLAPS_SUCCESS';
export const UPDATE_TWEET_CLAPS_FAILURE = 'UPDATE_TWEET_CLAPS_FAILURE';
