export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE';

export const FETCH_USERS_DETAILS_REQUEST = 'FETCH_USERS_DETAILS_REQUEST';
export const FETCH_USERS_DETAILS_SUCCESS = 'FETCH_USERS_DETAILS_SUCCESS';
export const FETCH_USERS_DETAILS_FAILURE = 'FETCH_USERS_DETAILS_FAILURE';
